 const data = [{
    id: 1,
    text: '¿Que es el dinero?',
    choices: ["PERMITE CONOCER CUANTO VALEN LAS COSAS Y ASI COMPRAR LO QUE NECESITAMOS O DESEAMOS", "LO INVENTARON LAS PERSONAS PARA GASTAR Y TENER DEUDAS", "SON PAPELES QUE LE DAN A MI PAPÁ POR NO ESTAR EN LA CASA", "SE PUEDE COMPRAR TODO, HASTA LA FELICIDAD!"],
    answer:"SE PUEDE COMPRAR TODO, HASTA LA FELICIDAD"
    },
    {
        id: 1,
        text: '¿Que es el perro?',
        choices: ["PERMITE CONOCER CUANTO VALEN LAS COSAS Y ASI COMPRAR LO QUE NECESITAMOS O DESEAMOS", "LO INVENTARON LAS PERSONAS PARA GASTAR Y TENER DEUDAS", "SON PAPELES QUE LE DAN A MI PAPÁ POR NO ESTAR EN LA CASA", "SE PUEDE COMPRAR TODO, HASTA LA FELICIDAD!"],
        answer:"SE PUEDE COMPRAR TODO, HASTA LA FELICIDAD"
        },

]

export default data;